config/routes.rb
Invitus::Application.routes.draw do
  resources :events_users

  resources :events

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :end_time, :image_url, :location, :map_url, :start_time, :title, :description, :map_html, :active
  validates_presence_of :title, :description, :start_time
  #has_and_belongs_to_many :users
  has_many :events_users
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  # GET /events
  # GET /events.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :map_url %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.input :image_url %>
  <%= f.input :description %>
  <%= f.input :map_html %>
  <%= f.input :active %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:map_url) %></th>
      <th><%= model_class.human_attribute_name(:start_time) %> - <%= model_class.human_attribute_name(:end_time) %></th>
      <th><%= model_class.human_attribute_name(:image_url) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:map_html) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.title %></td>
        <td><%= event.location %></td>
<% if event.map_url.length > 21 %>
        <td><%= event.map_url[0..20] %>...</td>
<% elsif event.map_url.length == 0 %>
        <td></td>
<% else %>
        <td><%= event.map_url[0..20] %></td>
<% end %>
        <td><%= event.start_time %> - <%= event.end_time %></td>
<% if event.image_url.length > 21 %>
        <td><%= event.image_url[0..20] %>...</td>
<% elsif event.image_url.length == 0 %>
        <td></td>
<% else %>
        <td><%= event.image_url[0..20] %></td>
<% end %>
<% if event.description.length > 21 %>
        <td><%= event.description[0..20] %>...</td>
<% elsif event.description.length == 0 %>
        <td></td>
<% else %>
        <td><%= event.description[0..20] %></td>
<% end %>
<% if event.map_html.length > 21 %>
        <td><%= event.map_html[0..20] %>...</td>
<% elsif event.map_html.length == 0 %>
        <td></td>
<% else %>
        <td><%= event.map_html[0..20] %></td>
<% end %>
        <td><%= event.active %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @event.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @event.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:map_url) %>:</strong></dt>
  <dd><%= @event.map_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_time) %>:</strong></dt>
  <dd><%= @event.start_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_time) %>:</strong></dt>
  <dd><%= @event.end_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_url) %>:</strong></dt>
  <dd><%= @event.image_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:map_html) %>:</strong></dt>
  <dd><%= @event.map_html %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @event.active %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>